#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Alexa  Home Automation"
  https://create.arduino.cc/cloud/things/e2a83915-4994-45a2-88d7-c6943d5cf582 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float GAS_Detect;
  CloudLight Light_ON_OFF;
  CloudSwitch LED_light;
  CloudTemperatureSensor Temparature;
  int Humidity;
  bool Buzzer;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <DHT11.h>

int mq2_pin = 35;
int DHT_pin = 4;
int BUZ_pin = 12;
int Led_pin = 14;
int LDR_pin = 34;

DHT11 dht11(DHT_pin);

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  pinMode(LDR_pin,INPUT);
  pinMode(mq2_pin,INPUT);
  pinMode(BUZ_pin, OUTPUT);
  pinMode(Led_pin, OUTPUT);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  //============================================= GAS Detected =========================
  GAS_Detect = analogRead(mq2_pin);
  if(GAS_Detect>2500){
    Buzzer = 1;
  }
  if(Buzzer==1){
    digitalWrite(BUZ_pin,HIGH);
  }
  else{
    digitalWrite(BUZ_pin,LOW);
  }

  //============================================= LED with LDR =========================
  Light_ON_OFF = digitalRead(LDR_pin);
  if(Light_ON_OFF==1){
    Serial.println("room is Dark nedd to on the LED_light");
  }
  
  if(LED_light){
    digitalWrite(Led_pin,HIGH);
  }
  else{
    digitalWrite(Led_pin,LOW);
  }

  //=================================== weather ========================
  Temparature = dht11.readTemperature();
  Humidity = dht11.readHumidity();
}

/*
  Since Temparature is READ_WRITE variable, onTemparatureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTemparatureChange()  {
  // Add your code here to act upon Temparature change
}
/*
  Since Humidity is READ_WRITE variable, onHumidityChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHumidityChange()  {
  // Add your code here to act upon Humidity change
}
/*
  Since Buzzer is READ_WRITE variable, onBuzzerChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBuzzerChange()  {
  // Add your code here to act upon Buzzer change
}
/*
  Since LEDLight is READ_WRITE variable, onLEDLightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLEDLightChange()  {
  // Add your code here to act upon LEDLight change
  
}



