// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "2ecb6f9b-9d5d-4bc7-a29a-d2def6e0f35b";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLEDLightChange();
void onTemparatureChange();
void onHumidityChange();
void onBuzzerChange();

float GAS_Detect;
CloudLight Light_ON_OFF;
CloudSwitch LED_light;
CloudTemperatureSensor Temparature;
int Humidity;
bool Buzzer;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(GAS_Detect, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(Light_ON_OFF, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(LED_light, READWRITE, ON_CHANGE, onLEDLightChange);
  ArduinoCloud.addProperty(Temparature, READWRITE, ON_CHANGE, onTemparatureChange);
  ArduinoCloud.addProperty(Humidity, READWRITE, ON_CHANGE, onHumidityChange);
  ArduinoCloud.addProperty(Buzzer, READWRITE, ON_CHANGE, onBuzzerChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
